export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';

export const PURCHASE_PET = 'PURCHASE_PET';
export const PURCHASE_PET_START = 'PURCHASE_PET_START';
export const PURCHASE_PET_SUCCESS = 'PURCHASE_PET_SUCCESS';
export const PURCHASE_PET_FAILED = 'PURCHASE_PET_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const INIT_BREEDS = 'INIT_BREEDS';
export const INIT_CATEGORY = 'INIT_CATEGORY';
export const INIT_PETS = 'INIT_PETS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const SET_PETS = 'SET_PETS';
export const FETCH_PETS_FAILED = 'FETCH_PETS_FAILED';
